force-app/main/default/objects/Library_Book__c/Library_Book__c.object-meta.xml
<CustomObject>
    <label>Library Book</label>
    <nameField>
        <label>Library Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Library_Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Library_Book_Loan__c/Library_Book_Loan__c.object-meta.xml
<CustomObject>
    <label>Library Book Loan</label>
    <nameField>
        <label>Library Book Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Books Loan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Library_Book_Loan__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <referenceTo>Library_Book__c</referenceTo>
    <relationshipLabel>Library Books Loan</relationshipLabel>
    <relationshipName>Library_Books_Loan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Library_Book_Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Library Books Loan</relationshipLabel>
    <relationshipName>Library_Books_Loan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LibraryService.cls
public with sharing class LibraryService {
    @AuraEnabled(cacheable=true)
    public static List<Library_Book__c> searchBooks(String searchTerm) {

        String formattedSearchTerm = '%' + searchTerm + '%';
        List<Library_Book__c> books = [SELECT Id, Title__c, Author__c, Available_Copies__c
                                       FROM Library_Book__c
                                       WHERE Title__c LIKE :formattedSearchTerm OR Author__c LIKE :formattedSearchTerm
                                       LIMIT 10];
        return books;
    }

    @AuraEnabled(cacheable=true)
    public static List<Contact> searchContacts(String searchTerm) {
        String formattedSearchTerm = '%' + searchTerm + '%';
        return [SELECT Id, FirstName, LastName 
                FROM Contact 
                WHERE FirstName LIKE :formattedSearchTerm OR LastName LIKE :formattedSearchTerm
                LIMIT 10];
    }

    @AuraEnabled
public static Boolean loanBook(Id bookId, Id borrowerId) {
    Library_Book_Loan__c loan = new Library_Book_Loan__c(
        Borrower__c = borrowerId,
        Book__c = bookId,
        Loan_Start_Date__c = Date.today()
    );
    insert loan;
    return true; 
}

}